fix for #9 & #12
team-supercharge/ShimmerLayout pull request #16
Opened 2017-07-24 07:17 UTC by k0shk0sh

2017-07-24 07:38 UTC, veghtomi requested changes

2017-07-24 07:38 UTC, veghtomi commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
> +    @Override public void setVisibility(int visibility) {
@override should be in a different line like in other cases.

2017-07-24 07:38 UTC, veghtomi commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
> +    private void removeGlobalListener(ViewTreeObserver.OnGlobalLayoutListener listener) {
Call this method removeGlobalLayoutListener(...)

2017-07-24 07:40 UTC, k0shk0sh commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
> +    @Override public void setVisibility(int visibility) {
Ooops, that slipped by my own style 😕

2017-07-24 08:33 UTC, k0shk0sh commented
@veghtomi please review & update accordingly.

2017-07-25 09:22 UTC, veghtomi approved these changes

2017-07-25 09:25 UTC, merged