Fix mask size
team-supercharge/ShimmerLayout pull request #19
Opened 2017-08-01 20:33 UTC by szugyi

Calculated mask bitmaps before:
![original1](https://user-images.githubusercontent.com/3823933/28845769-66a31b62-7709-11e7-9d76-95e64a086e22.png)
![original2](https://user-images.githubusercontent.com/3823933/28845767-665d4524-7709-11e7-9fb1-8410c345cd1e.png)
![original3](https://user-images.githubusercontent.com/3823933/28845768-6662f2bc-7709-11e7-982e-2fc9e6edbcaf.png)

After:
![fixed1](https://user-images.githubusercontent.com/3823933/28845807-7d51f7a2-7709-11e7-86c1-aa73c4ff29b3.png)
![fixed2](https://user-images.githubusercontent.com/3823933/28845808-7d53e878-7709-11e7-924b-8fed384ffce8.png)
![fixed3](https://user-images.githubusercontent.com/3823933/28845806-7d496286-7709-11e7-92f4-7b28b275427b.png)

2017-08-02 07:12 UTC, veghtomi requested changes

2017-08-02 07:12 UTC, veghtomi commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
> +            return new Rect(0, 0, getWidth(), getHeight());
@szugyi if the angle is zero, then the width can be the original getWidth() / 2 since it will be a vertical line, right?

2017-08-02 07:20 UTC, veghtomi requested changes

2017-08-02 07:20 UTC, veghtomi commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
Would you also create a java doc comment here, so users of this library would know the min and the max angle?

2017-08-02 21:43 UTC, szugyi commented
@veghtomi PR updated according to change requests

2017-08-03 19:15 UTC, veghtomi approved these changes

2017-08-03 19:15 UTC, merged

2017-08-03 19:30 UTC, veghtomi commented
Nice code, nice work! @szugyi