Add reverse animation and widen angle values
team-supercharge/ShimmerLayout pull request #49
Opened 2018-03-06 11:32 UTC by veghtomi

2018-03-06 13:07 UTC, szugyi requested changes

2018-03-06 13:07 UTC, szugyi commented on shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java
> +    private int[] createLinearGradientVector() {
As I can see the only difference between the two vectors is whether or not we use the height of the view in the LinearGradient creation. We could extract this into a variable before we create the LinearGradient and then use the value in the constructor in addition to the values calculated by the trigonometric functions.

2018-03-07 15:29 UTC, veghtomi commented
@szugyi Change request is fixed, you can check and merge!

2018-03-07 19:59 UTC, szugyi approved these changes

2018-03-07 20:00 UTC, merged